/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountryCountryRouteImport } from './routes/country.$country'
import { Route as ArtistSlugRouteImport } from './routes/artist.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCountryRoute = CountryCountryRouteImport.update({
  id: '/country/$country',
  path: '/country/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistSlugRoute = ArtistSlugRouteImport.update({
  id: '/artist/$slug',
  path: '/artist/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artist/$slug': typeof ArtistSlugRoute
  '/country/$country': typeof CountryCountryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artist/$slug': typeof ArtistSlugRoute
  '/country/$country': typeof CountryCountryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artist/$slug': typeof ArtistSlugRoute
  '/country/$country': typeof CountryCountryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/artist/$slug' | '/country/$country'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/artist/$slug' | '/country/$country'
  id: '__root__' | '/' | '/artist/$slug' | '/country/$country'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtistSlugRoute: typeof ArtistSlugRoute
  CountryCountryRoute: typeof CountryCountryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country/$country': {
      id: '/country/$country'
      path: '/country/$country'
      fullPath: '/country/$country'
      preLoaderRoute: typeof CountryCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$slug': {
      id: '/artist/$slug'
      path: '/artist/$slug'
      fullPath: '/artist/$slug'
      preLoaderRoute: typeof ArtistSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtistSlugRoute: ArtistSlugRoute,
  CountryCountryRoute: CountryCountryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
