// AUTO-GENERATED by server/scripts/indexMusicFolder.ts — DO NOT EDIT BY HAND.
// Regenerate with:  cd server && npm run index-music
import type { Artist, Country, Song } from "@/lib/types";

export const COUNTRIES: Country[] = [
  {
    "name": "France",
    "code": "FR",
    "flag": "🇫🇷",
    "continent": "Europe",
    "lat": 46.23,
    "lng": 2.21
  }
];

export const ARTISTS: Artist[] = [
  {
    "slug": "charles-aznavour",
    "name": "Charles Aznavour",
    "country": "France",
    "countryCode": "FR",
    "continent": "Europe",
    "genres": [
      "Chanson FrançAise"
    ],
    "bio": "Charles Aznavour — France.",
    "foundedYear": 2000,
    "image": "https://picsum.photos/seed/charles-aznavour/600/600",
    "banner": "https://picsum.photos/seed/charles-aznavour-bn/1600/600",
    "followers": 0,
    "socials": {},
    "songs": [
      {
        "id": "charles-aznavour_charles-aznavour-les-deux-guitares",
        "title": "Charles Aznavour         Les Deux Guitares",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20%20%20-%20%20%20%20%20Les%20Deux%20Guitares.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20%20%20-%20%20%20%20%20Les%20Deux%20Guitares.mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-les-deux-guitares/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-bon-anniversaire",
        "title": "Charles Aznavour    Bon Anniversaire",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20%20Bon%20Anniversaire.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20%20Bon%20Anniversaire.mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-bon-anniversaire/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-le-palais-de-nos-chimeres",
        "title": "Charles Aznavour    Le Palais De Nos Chimeres",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20%20Le%20Palais%20De%20Nos%20Chimeres.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20%20Le%20Palais%20De%20Nos%20Chimeres.mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-le-palais-de-nos-chimeres/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-a-ma-fille",
        "title": "Charles Aznavour   A Ma Fille",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20A%20Ma%20Fille.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20A%20Ma%20Fille.mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-a-ma-fille/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-comme-ils-disent-audio-officiel",
        "title": "Charles Aznavour   Comme Ils Disent (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Comme%20ils%20disent%20(Audio%20Officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Comme%20ils%20disent%20(Audio%20Officiel).mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-comme-ils-disent-audio-officiel/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-desormais-audio-officiel",
        "title": "Charles Aznavour   DéSormais (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20D%C3%A9sormais%20(Audio%20Officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20D%C3%A9sormais%20(Audio%20Officiel).mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-desormais-audio-officiel/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-emmenez-moi-official-lyric-video",
        "title": "Charles Aznavour   Emmenez Moi (Official Lyric Video)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Emmenez-moi%20(Official%20Lyric%20Video).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Emmenez-moi%20(Official%20Lyric%20Video).mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-emmenez-moi-official-lyric-video/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-et-pourtant-audio-officiel",
        "title": "Charles Aznavour   Et Pourtant (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Et%20pourtant%20(Audio%20Officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Et%20pourtant%20(Audio%20Officiel).mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-et-pourtant-audio-officiel/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-for-me-formidable-audio-officiel",
        "title": "Charles Aznavour   For Me Formidable (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20For%20Me%20Formidable%20(Audio%20Officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20For%20Me%20Formidable%20(Audio%20Officiel).mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-for-me-formidable-audio-officiel/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-hier-encore-audio-officiel",
        "title": "Charles Aznavour   Hier Encore (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Hier%20encore%20(Audio%20Officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Hier%20encore%20(Audio%20Officiel).mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-hier-encore-audio-officiel/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-il-faut-savoir",
        "title": "Charles Aznavour   Il Faut Savoir",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Il%20Faut%20Savoir.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Il%20Faut%20Savoir.mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-il-faut-savoir/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-il-te-suffisait-que-je-t-aime",
        "title": "Charles Aznavour   Il Te Suffisait Que Je T'Aime",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Il%20Te%20Suffisait%20Que%20Je%20T'aime.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Il%20Te%20Suffisait%20Que%20Je%20T'aime.mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-il-te-suffisait-que-je-t-aime/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-je-m-voyais-deja-audio-officiel",
        "title": "Charles Aznavour   Je M'Voyais DéJà (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Je%20m'voyais%20d%C3%A9j%C3%A0%20(Audio%20Officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Je%20m'voyais%20d%C3%A9j%C3%A0%20(Audio%20Officiel).mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-je-m-voyais-deja-audio-officiel/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-je-t-attends",
        "title": "Charles Aznavour   Je T'Attends",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Je%20t'Attends.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Je%20t'Attends.mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-je-t-attends/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-la-boheme-official-lyrics-video",
        "title": "Charles Aznavour   La BohèMe (Official Lyrics Video)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20La%20boh%C3%A8me%20(Official%20Lyrics%20Video).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20La%20boh%C3%A8me%20(Official%20Lyrics%20Video).mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-la-boheme-official-lyrics-video/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-la-mamma-audio-officiel",
        "title": "Charles Aznavour   La Mamma (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20La%20Mamma%20(Audio%20Officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20La%20Mamma%20(Audio%20Officiel).mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-la-mamma-audio-officiel/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-les-comediens-audio-officiel",
        "title": "Charles Aznavour   Les ComéDiens (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Les%20com%C3%A9diens%20(Audio%20Officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Les%20com%C3%A9diens%20(Audio%20Officiel).mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-les-comediens-audio-officiel/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-les-plaisirs-demodes-audio-officiel",
        "title": "Charles Aznavour   Les Plaisirs DéModéS (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Les%20plaisirs%20d%C3%A9mod%C3%A9s%20(Audio%20Officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Les%20plaisirs%20d%C3%A9mod%C3%A9s%20(Audio%20Officiel).mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-les-plaisirs-demodes-audio-officiel/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-mes-emmerdes-audio-officiel",
        "title": "Charles Aznavour   Mes Emmerdes (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Mes%20emmerdes%20(Audio%20Officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Mes%20emmerdes%20(Audio%20Officiel).mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-mes-emmerdes-audio-officiel/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-mourir-d-aimer-audio-officiel",
        "title": "Charles Aznavour   Mourir D'Aimer (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Mourir%20d'aimer%20(Audio%20Officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Mourir%20d'aimer%20(Audio%20Officiel).mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-mourir-d-aimer-audio-officiel/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-non-je-n-ai-rien-oublie-audio-officiel",
        "title": "Charles Aznavour   Non Je N'Ai Rien Oublié (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Non%20je%20n'ai%20rien%20oubli%C3%A9%20(Audio%20Officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Non%20je%20n'ai%20rien%20oubli%C3%A9%20(Audio%20Officiel).mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-non-je-n-ai-rien-oublie-audio-officiel/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-parce-que-tu-crois-audio-officiel-paroles",
        "title": "Charles Aznavour   Parce Que Tu Crois (Audio Officiel + Paroles)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Parce%20que%20tu%20crois%20(Audio%20Officiel%20+%20Paroles).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Parce%20que%20tu%20crois%20(Audio%20Officiel%20+%20Paroles).mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-parce-que-tu-crois-audio-officiel-paroles/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-paris-au-mois-d-aout",
        "title": "Charles Aznavour   Paris Au Mois D'AoûT",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Paris%20Au%20Mois%20D'ao%C3%BBt.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Paris%20Au%20Mois%20D'ao%C3%BBt.mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-paris-au-mois-d-aout/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-plus-bleu-que-tes-yeux-audio-officiel",
        "title": "Charles Aznavour   Plus Bleu Que Tes Yeux (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Plus%20bleu%20que%20tes%20yeux%20(Audio%20officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Plus%20bleu%20que%20tes%20yeux%20(Audio%20officiel).mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-plus-bleu-que-tes-yeux-audio-officiel/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-que-c-est-triste-venise-audio-officiel",
        "title": "Charles Aznavour   Que C'Est Triste Venise (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Que%20c'est%20triste%20Venise%20(Audio%20Officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Que%20c'est%20triste%20Venise%20(Audio%20Officiel).mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-que-c-est-triste-venise-audio-officiel/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-she-official-music-video",
        "title": "Charles Aznavour   She (Official Music Video)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20She%20(Official%20Music%20Video).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20She%20(Official%20Music%20Video).mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-she-official-music-video/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-sur-ma-vie",
        "title": "Charles Aznavour   Sur Ma Vie",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Sur%20Ma%20Vie.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Sur%20Ma%20Vie.mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-sur-ma-vie/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-toi-et-moi",
        "title": "Charles Aznavour   Toi Et Moi",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Toi%20Et%20Moi.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Toi%20Et%20Moi.mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-toi-et-moi/600/600"
      },
      {
        "id": "charles-aznavour_charles-aznavour-tout-s-en-va",
        "title": "Charles Aznavour   Tout S'En Va",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Tout%20s'en%20va.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Charles%20Aznavour%20-%20Tout%20s'en%20va.mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_charles-aznavour-tout-s-en-va/600/600"
      },
      {
        "id": "charles-aznavour_j-en-deduis-que-je-t-aime",
        "title": "J'En DéDuis Que Je T'Aime",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/J'en%20d%C3%A9duis%20que%20je%20t'aime.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/J'en%20d%C3%A9duis%20que%20je%20t'aime.mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_j-en-deduis-que-je-t-aime/600/600"
      },
      {
        "id": "charles-aznavour_liane-foly-charles-aznavour-clip-la-belle-et-la-bete-1992",
        "title": "LIANE FOLY ⧸ CHARLES AZNAVOUR   Clip ＂La Belle Et La BêTe＂ (1992)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/LIANE%20FOLY%20%E2%A7%B8%20CHARLES%20AZNAVOUR%20-%20clip%20%EF%BC%82La%20Belle%20et%20la%20B%C3%AAte%EF%BC%82%20(1992).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/LIANE%20FOLY%20%E2%A7%B8%20CHARLES%20AZNAVOUR%20-%20clip%20%EF%BC%82La%20Belle%20et%20la%20B%C3%AAte%EF%BC%82%20(1992).mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_liane-foly-charles-aznavour-clip-la-belle-et-la-bete-1992/600/600"
      },
      {
        "id": "charles-aznavour_nous-nous-reverrons-un-jour-ou-l-autre-charles-aznavour",
        "title": "Nous Nous Reverrons Un Jour Ou L'Autre   Charles Aznavour",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Nous%20nous%20reverrons%20un%20jour%20ou%20l'autre%20%20%20Charles%20Aznavour.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Nous%20nous%20reverrons%20un%20jour%20ou%20l'autre%20%20%20Charles%20Aznavour.mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_nous-nous-reverrons-un-jour-ou-l-autre-charles-aznavour/600/600"
      },
      {
        "id": "charles-aznavour_o-toi-la-vie",
        "title": "Ô Toi La Vie",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/%C3%94%20toi%20la%20vie.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/%C3%94%20toi%20la%20vie.mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_o-toi-la-vie/600/600"
      },
      {
        "id": "charles-aznavour_patrick-bruel-charles-aznavour-menilmontant-audio",
        "title": "Patrick Bruel, Charles Aznavour   MéNilmontant (Audio)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Patrick%20Bruel,%20Charles%20Aznavour%20-%20M%C3%A9nilmontant%20(Audio).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Patrick%20Bruel,%20Charles%20Aznavour%20-%20M%C3%A9nilmontant%20(Audio).mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_patrick-bruel-charles-aznavour-menilmontant-audio/600/600"
      },
      {
        "id": "charles-aznavour_quand-on-s-aime",
        "title": "Quand On S'Aime",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Quand%20on%20s'aime.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Quand%20on%20s'aime.mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_quand-on-s-aime/600/600"
      },
      {
        "id": "charles-aznavour_sa-jeunesse-reenregistrement-1964",
        "title": "Sa Jeunesse (RéEnregistrement 1964)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Sa%20jeunesse%20(R%C3%A9enregistrement%201964).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Sa%20jeunesse%20(R%C3%A9enregistrement%201964).mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_sa-jeunesse-reenregistrement-1964/600/600"
      },
      {
        "id": "charles-aznavour_viens-pleurer-au-creux-de-mon-epaule-reenregistrement-1964",
        "title": "Viens Pleurer Au Creux De Mon éPaule (RéEnregistrement 1964)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Viens%20pleurer%20au%20creux%20de%20mon%20%C3%A9paule%20(R%C3%A9enregistrement%201964).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Charles%20Aznavour/Viens%20pleurer%20au%20creux%20de%20mon%20%C3%A9paule%20(R%C3%A9enregistrement%201964).mp3",
        "artistSlug": "charles-aznavour",
        "artistName": "Charles Aznavour",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/charles-aznavour_viens-pleurer-au-creux-de-mon-epaule-reenregistrement-1964/600/600"
      }
    ]
  },
  {
    "slug": "christophe",
    "name": "Christophe",
    "country": "France",
    "countryCode": "FR",
    "continent": "Europe",
    "genres": [
      "Chanson FrançAise"
    ],
    "bio": "Christophe — France.",
    "foundedYear": 2000,
    "image": "https://picsum.photos/seed/christophe/600/600",
    "banner": "https://picsum.photos/seed/christophe-bn/1600/600",
    "followers": 0,
    "socials": {},
    "songs": [
      {
        "id": "christophe_boule-de-flipper",
        "title": "Boule De Flipper",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Boule%20de%20flipper.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Boule%20de%20flipper.mp3",
        "artistSlug": "christophe",
        "artistName": "Christophe",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe_boule-de-flipper/600/600"
      },
      {
        "id": "christophe_christophe-aline-1979",
        "title": "Christophe   Aline (1979)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Christophe%20-%20Aline%20(1979).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Christophe%20-%20Aline%20(1979).mp3",
        "artistSlug": "christophe",
        "artistName": "Christophe",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe_christophe-aline-1979/600/600"
      },
      {
        "id": "christophe_christophe-dangereuse",
        "title": "Christophe   Dangereuse",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Christophe%20-%20Dangereuse.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Christophe%20-%20Dangereuse.mp3",
        "artistSlug": "christophe",
        "artistName": "Christophe",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe_christophe-dangereuse/600/600"
      },
      {
        "id": "christophe_christophe-les-marionnettes",
        "title": "Christophe   Les Marionnettes",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Christophe%20-%20Les%20marionnettes.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Christophe%20-%20Les%20marionnettes.mp3",
        "artistSlug": "christophe",
        "artistName": "Christophe",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe_christophe-les-marionnettes/600/600"
      },
      {
        "id": "christophe_christophe-senorita-1974",
        "title": "Christophe   SeñOrita (1974)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Christophe%20-%20Se%C3%B1orita%20(1974).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Christophe%20-%20Se%C3%B1orita%20(1974).mp3",
        "artistSlug": "christophe",
        "artistName": "Christophe",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe_christophe-senorita-1974/600/600"
      },
      {
        "id": "christophe_daisy",
        "title": "Daisy",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Daisy.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Daisy.mp3",
        "artistSlug": "christophe",
        "artistName": "Christophe",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe_daisy/600/600"
      },
      {
        "id": "christophe_eddy-mitchell-la-meme-tribu-2",
        "title": "Eddy Mitchell   La MêMe Tribu 2",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Eddy%20Mitchell%20-%20La%20M%C3%AAme%20Tribu%202.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Eddy%20Mitchell%20-%20La%20M%C3%AAme%20Tribu%202.mp3",
        "artistSlug": "christophe",
        "artistName": "Christophe",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe_eddy-mitchell-la-meme-tribu-2/600/600"
      },
      {
        "id": "christophe_la-dolce-vita",
        "title": "La Dolce Vita",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/La%20dolce%20vita.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/La%20dolce%20vita.mp3",
        "artistSlug": "christophe",
        "artistName": "Christophe",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe_la-dolce-vita/600/600"
      },
      {
        "id": "christophe_les-mots-bleus",
        "title": "Les Mots Bleus",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Les%20mots%20bleus.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Les%20mots%20bleus.mp3",
        "artistSlug": "christophe",
        "artistName": "Christophe",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe_les-mots-bleus/600/600"
      },
      {
        "id": "christophe_les-paradis-perdus",
        "title": "Les Paradis Perdus",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Les%20paradis%20perdus.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Les%20paradis%20perdus.mp3",
        "artistSlug": "christophe",
        "artistName": "Christophe",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe_les-paradis-perdus/600/600"
      },
      {
        "id": "christophe_main-dans-la-main",
        "title": "Main Dans La Main",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Main%20dans%20la%20main.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Main%20dans%20la%20main.mp3",
        "artistSlug": "christophe",
        "artistName": "Christophe",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe_main-dans-la-main/600/600"
      },
      {
        "id": "christophe_ne-raccroche-pas",
        "title": "Ne Raccroche Pas",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Ne%20raccroche%20pas.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Ne%20raccroche%20pas.mp3",
        "artistSlug": "christophe",
        "artistName": "Christophe",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe_ne-raccroche-pas/600/600"
      },
      {
        "id": "christophe_ocean-d-amour",
        "title": "OcéAn D'Amour",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Oc%C3%A9an%20d'amour.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Oc%C3%A9an%20d'amour.mp3",
        "artistSlug": "christophe",
        "artistName": "Christophe",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe_ocean-d-amour/600/600"
      },
      {
        "id": "christophe_petite-fille-du-soleil",
        "title": "Petite Fille Du Soleil",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Petite%20fille%20du%20soleil.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Petite%20fille%20du%20soleil.mp3",
        "artistSlug": "christophe",
        "artistName": "Christophe",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe_petite-fille-du-soleil/600/600"
      },
      {
        "id": "christophe_succes-fou",
        "title": "SuccèS Fou",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Succ%C3%A8s%20fou.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Succ%C3%A8s%20fou.mp3",
        "artistSlug": "christophe",
        "artistName": "Christophe",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe_succes-fou/600/600"
      },
      {
        "id": "christophe_tangerine",
        "title": "Tangerine",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Tangerine.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe/Tangerine.mp3",
        "artistSlug": "christophe",
        "artistName": "Christophe",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe_tangerine/600/600"
      }
    ]
  },
  {
    "slug": "christophe-mae",
    "name": "Christophe Maé",
    "country": "France",
    "countryCode": "FR",
    "continent": "Europe",
    "genres": [
      "Chanson FrançAise"
    ],
    "bio": "Christophe Maé — France.",
    "foundedYear": 2000,
    "image": "https://picsum.photos/seed/christophe-mae/600/600",
    "banner": "https://picsum.photos/seed/christophe-mae-bn/1600/600",
    "followers": 0,
    "socials": {},
    "songs": [
      {
        "id": "christophe-mae_a-qui-la-faute",
        "title": "À Qui La Faute",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/%C3%80%20qui%20la%20faute.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/%C3%80%20qui%20la%20faute.mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_a-qui-la-faute/600/600"
      },
      {
        "id": "christophe-mae_bouquet-de-roses",
        "title": "Bouquet De Roses",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Bouquet%20de%20roses.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Bouquet%20de%20roses.mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_bouquet-de-roses/600/600"
      },
      {
        "id": "christophe-mae_c-est-drole-la-vie",
        "title": "C'Est DrôLe La Vie",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/C'est%20dr%C3%B4le%20la%20vie.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/C'est%20dr%C3%B4le%20la%20vie.mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_c-est-drole-la-vie/600/600"
      },
      {
        "id": "christophe-mae_ca-marche",
        "title": "ÇA Marche",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/%C3%87a%20marche.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/%C3%87a%20marche.mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_ca-marche/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-belle-demoiselle-audio-officiel",
        "title": "Christophe Maé   Belle Demoiselle (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Belle%20demoiselle%20(Audio%20officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Belle%20demoiselle%20(Audio%20officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-belle-demoiselle-audio-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-c-est-ma-terre-audio-officiel",
        "title": "Christophe Maé   C'Est Ma Terre (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20C'est%20ma%20terre%20(Audio%20officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20C'est%20ma%20terre%20(Audio%20officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-c-est-ma-terre-audio-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-ca-fait-mal-audio-officiel",
        "title": "Christophe Maé   ÇA Fait Mal (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20%C3%87a%20fait%20mal%20(Audio%20officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20%C3%87a%20fait%20mal%20(Audio%20officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-ca-fait-mal-audio-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-casting-paroles",
        "title": "Christophe Maé   Casting (Paroles)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Casting%20(Paroles).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Casting%20(Paroles).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-casting-paroles/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-charly-audio-officiel",
        "title": "Christophe Maé   Charly (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Charly%20(Audio%20officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Charly%20(Audio%20officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-charly-audio-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-dingue-dingue-dingue-audio-officiel",
        "title": "Christophe Maé   Dingue, Dingue, Dingue (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Dingue,%20dingue,%20dingue%20(Audio%20Officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Dingue,%20dingue,%20dingue%20(Audio%20Officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-dingue-dingue-dingue-audio-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-il-est-ou-le-bonheur-clip-officiel",
        "title": "Christophe Maé   Il Est Où Le Bonheur (Clip Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Il%20est%20o%C3%B9%20le%20bonheur%20(Clip%20officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Il%20est%20o%C3%B9%20le%20bonheur%20(Clip%20officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-il-est-ou-le-bonheur-clip-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-j-ai-laisse-audio-officiel",
        "title": "Christophe Maé   J'Ai Laissé (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20J'ai%20laiss%C3%A9%20(Audio%20Officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20J'ai%20laiss%C3%A9%20(Audio%20Officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-j-ai-laisse-audio-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-j-ai-vu-la-vie-audio-officiel",
        "title": "Christophe Maé   J'Ai Vu La Vie (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20J'ai%20vu%20la%20vie%20(Audio%20Officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20J'ai%20vu%20la%20vie%20(Audio%20Officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-j-ai-vu-la-vie-audio-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-je-me-lache-audio-officiel",
        "title": "Christophe Maé   Je Me LâChe (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Je%20me%20l%C3%A2che%20(Audio%20Officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Je%20me%20l%C3%A2che%20(Audio%20Officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-je-me-lache-audio-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-je-veux-du-bonheur-audio-officiel",
        "title": "Christophe Maé   Je Veux Du Bonheur (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Je%20veux%20du%20bonheur%20(Audio%20officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Je%20veux%20du%20bonheur%20(Audio%20officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-je-veux-du-bonheur-audio-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-l-amour-feat-amadou-mariam-paroles",
        "title": "Christophe Maé   L'Amour Feat. Amadou & Mariam (Paroles)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20L'amour%20feat.%20Amadou%20&%20Mariam%20(Paroles).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20L'amour%20feat.%20Amadou%20&%20Mariam%20(Paroles).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-l-amour-feat-amadou-mariam-paroles/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-la-lune-paroles",
        "title": "Christophe Maé   La Lune (Paroles)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Mae%CC%81%20-%20La%20lune%20(Paroles).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Mae%CC%81%20-%20La%20lune%20(Paroles).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-la-lune-paroles/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-la-parisienne-clip-officiel",
        "title": "Christophe Maé   La Parisienne (Clip Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20La%20Parisienne%20(Clip%20officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20La%20Parisienne%20(Clip%20officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-la-parisienne-clip-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-la-poupee-clip-officiel",
        "title": "Christophe Maé   La PoupéE (Clip Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20La%20Poup%C3%A9e%20(Clip%20Officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20La%20Poup%C3%A9e%20(Clip%20Officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-la-poupee-clip-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-la-rumeur-clip-officiel",
        "title": "Christophe Maé   La Rumeur (Clip Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20La%20Rumeur%20(Clip%20Officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20La%20Rumeur%20(Clip%20Officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-la-rumeur-clip-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-la-vie-d-artiste-paroles",
        "title": "Christophe Maé   La Vie D'Artiste (Paroles)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20La%20vie%20d'artiste%20(Paroles).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20La%20vie%20d'artiste%20(Paroles).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-la-vie-d-artiste-paroles/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-lampedusa-audio-officiel",
        "title": "Christophe Maé   Lampedusa (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Mae%CC%81%20-%20Lampedusa%20(Audio%20officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Mae%CC%81%20-%20Lampedusa%20(Audio%20officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-lampedusa-audio-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-les-bougies-paroles",
        "title": "Christophe Maé   Les Bougies (Paroles)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Les%20bougies%20(Paroles).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Les%20bougies%20(Paroles).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-les-bougies-paroles/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-les-gens-clip-officiel",
        "title": "Christophe Maé   Les Gens (Clip Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Les%20Gens%20(Clip%20officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Les%20Gens%20(Clip%20officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-les-gens-clip-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-ma-douleur-ma-peine-clip-officiel",
        "title": "Christophe Maé   Ma Douleur, Ma Peine (Clip Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Ma%20douleur,%20Ma%20peine%20(Clip%20Officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Ma%20douleur,%20Ma%20peine%20(Clip%20Officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-ma-douleur-ma-peine-clip-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-maman-audio-officiel",
        "title": "Christophe Maé   Maman (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Maman%20(Audio%20officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Maman%20(Audio%20officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-maman-audio-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-manon-audio-officiel",
        "title": "Christophe Maé   Manon (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Manon%20(Audio%20Officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Manon%20(Audio%20Officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-manon-audio-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-marcel-clip-officiel",
        "title": "Christophe Maé   Marcel (Clip Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Marcel%20(Clip%20officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Marcel%20(Clip%20officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-marcel-clip-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-mon-p-tit-gars-audio-officiel",
        "title": "Christophe Maé   Mon P'Tit Gars (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Mon%20p'tit%20gars%20(Audio%20officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Mon%20p'tit%20gars%20(Audio%20officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-mon-p-tit-gars-audio-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-mon-paradis-audio-officiel",
        "title": "Christophe Maé   Mon Paradis (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Mon%20Paradis%20(Audio%20officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Mon%20Paradis%20(Audio%20officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-mon-paradis-audio-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-ne-m-abandonne-pas-audio-officiel",
        "title": "Christophe Maé   Ne M'Abandonne Pas (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Ne%20m'abandonne%20pas%20(Audio%20Officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Ne%20m'abandonne%20pas%20(Audio%20Officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-ne-m-abandonne-pas-audio-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-on-s-attache-audio-officiel",
        "title": "Christophe Maé   On S'Attache (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20On%20s'attache%20(Audio%20officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20On%20s'attache%20(Audio%20officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-on-s-attache-audio-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-parce-qu-on-sait-jamais-audio-officiel",
        "title": "Christophe Maé   Parce Qu'On Sait Jamais (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Parce%20qu'on%20sait%20jamais%20(Audio%20officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Parce%20qu'on%20sait%20jamais%20(Audio%20officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-parce-qu-on-sait-jamais-audio-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-pourquoi-c-est-beau-audio-officiel",
        "title": "Christophe Maé   Pourquoi C'Est Beau... (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Pourquoi%20c'est%20beau...%20(Audio%20Officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Pourquoi%20c'est%20beau...%20(Audio%20Officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-pourquoi-c-est-beau-audio-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-tombe-sous-le-charme-audio-officiel",
        "title": "Christophe Maé   Tombé Sous Le Charme (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Tomb%C3%A9%20sous%20le%20charme%20(Audio%20officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Tomb%C3%A9%20sous%20le%20charme%20(Audio%20officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-tombe-sous-le-charme-audio-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-trop-jeune-paroles",
        "title": "Christophe Maé   Trop Jeune (Paroles)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Trop%20jeune%20(Paroles).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Trop%20jeune%20(Paroles).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-trop-jeune-paroles/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-un-peu-de-blues-audio-officiel",
        "title": "Christophe Maé   Un Peu De Blues (Audio Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Un%20peu%20de%20blues%20(Audio%20officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Un%20peu%20de%20blues%20(Audio%20officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-un-peu-de-blues-audio-officiel/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-y-a-du-soleil-paroles",
        "title": "Christophe Maé   Y'A Du Soleil (Paroles)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Y'a%20du%20soleil%20(Paroles).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20-%20Y'a%20du%20soleil%20(Paroles).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-y-a-du-soleil-paroles/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-ceuzany-pays-des-merveilles-paroles",
        "title": "Christophe Maé & Ceuzany   Pays Des Merveilles (Paroles)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20&%20Ceuzany%20-%20Pays%20des%20merveilles%20(Paroles).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20&%20Ceuzany%20-%20Pays%20des%20merveilles%20(Paroles).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-ceuzany-pays-des-merveilles-paroles/600/600"
      },
      {
        "id": "christophe-mae_christophe-mae-feat-youssou-n-dour-l-ours-paroles",
        "title": "Christophe Maé Feat. Youssou N'Dour   L'Ours (Paroles)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20feat.%20Youssou%20N'Dour%20-%20L'ours%20(Paroles).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Christophe%20Ma%C3%A9%20feat.%20Youssou%20N'Dour%20-%20L'ours%20(Paroles).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_christophe-mae-feat-youssou-n-dour-l-ours-paroles/600/600"
      },
      {
        "id": "christophe-mae_comme-avant",
        "title": "Comme Avant",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Comme%20avant.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Comme%20avant.mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_comme-avant/600/600"
      },
      {
        "id": "christophe-mae_comment-on-s-aime",
        "title": "Comment On S'Aime",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Comment%20on%20s'aime.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Comment%20on%20s'aime.mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_comment-on-s-aime/600/600"
      },
      {
        "id": "christophe-mae_et-vice-versailles",
        "title": "Et Vice Versailles",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Et%20vice%20Versailles.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Et%20vice%20Versailles.mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_et-vice-versailles/600/600"
      },
      {
        "id": "christophe-mae_florent-pagny-christophe-mae-et-un-jour-une-femme",
        "title": "Florent Pagny, Christophe Maé   Et Un Jour Une Femme",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Florent%20Pagny,%20Christophe%20Ma%C3%A9%20-%20Et%20un%20jour%20une%20femme.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Florent%20Pagny,%20Christophe%20Ma%C3%A9%20-%20Et%20un%20jour%20une%20femme.mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_florent-pagny-christophe-mae-et-un-jour-une-femme/600/600"
      },
      {
        "id": "christophe-mae_la-fin-de-l-ete",
        "title": "La Fin De L'éTé",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/La%20fin%20de%20l'%C3%A9t%C3%A9.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/La%20fin%20de%20l'%C3%A9t%C3%A9.mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_la-fin-de-l-ete/600/600"
      },
      {
        "id": "christophe-mae_veronique-sanson-christophe-mae-besoin-de-personne-clip-officiel",
        "title": "VéRonique Sanson, Christophe Maé   Besoin De Personne (Clip Officiel)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/V%C3%A9ronique%20Sanson,%20Christophe%20Ma%C3%A9%20-%20Besoin%20de%20personne%20(Clip%20officiel).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/V%C3%A9ronique%20Sanson,%20Christophe%20Ma%C3%A9%20-%20Besoin%20de%20personne%20(Clip%20officiel).mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_veronique-sanson-christophe-mae-besoin-de-personne-clip-officiel/600/600"
      },
      {
        "id": "christophe-mae_week-end-sur-deux",
        "title": "Week End Sur Deux",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Week-end%20sur%20deux.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Christophe%20Ma%C3%A9/Week-end%20sur%20deux.mp3",
        "artistSlug": "christophe-mae",
        "artistName": "Christophe Maé",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/christophe-mae_week-end-sur-deux/600/600"
      }
    ]
  },
  {
    "slug": "claude-francois",
    "name": "Claude FrançOis",
    "country": "France",
    "countryCode": "FR",
    "continent": "Europe",
    "genres": [
      "Chanson FrançAise"
    ],
    "bio": "Claude FrançOis — France.",
    "foundedYear": 2000,
    "image": "https://picsum.photos/seed/claude-francois/600/600",
    "banner": "https://picsum.photos/seed/claude-francois-bn/1600/600",
    "followers": 0,
    "socials": {},
    "songs": [
      {
        "id": "claude-francois_alexandrie-alexandra",
        "title": "Alexandrie Alexandra",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Alexandrie%20Alexandra.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Alexandrie%20Alexandra.mp3",
        "artistSlug": "claude-francois",
        "artistName": "Claude FrançOis",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/claude-francois_alexandrie-alexandra/600/600"
      },
      {
        "id": "claude-francois_celui-qui-reste",
        "title": "Celui Qui Reste",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Celui%20qui%20reste.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Celui%20qui%20reste.mp3",
        "artistSlug": "claude-francois",
        "artistName": "Claude FrançOis",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/claude-francois_celui-qui-reste/600/600"
      },
      {
        "id": "claude-francois_claude-francois-17-ans",
        "title": "Claude FrançOis   17 Ans",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%2017%20ans.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%2017%20ans.mp3",
        "artistSlug": "claude-francois",
        "artistName": "Claude FrançOis",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/claude-francois_claude-francois-17-ans/600/600"
      },
      {
        "id": "claude-francois_claude-francois-belinda-audio",
        "title": "Claude FrançOis   BéLinda (Audio)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20B%C3%A9linda%20(Audio).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20B%C3%A9linda%20(Audio).mp3",
        "artistSlug": "claude-francois",
        "artistName": "Claude FrançOis",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/claude-francois_claude-francois-belinda-audio/600/600"
      },
      {
        "id": "claude-francois_claude-francois-belles-belles-belles-official-lyric-video",
        "title": "Claude FrançOis   Belles Belles Belles (Official Lyric Video)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20Belles%20Belles%20Belles%20(Official%20Lyric%20Video).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20Belles%20Belles%20Belles%20(Official%20Lyric%20Video).mp3",
        "artistSlug": "claude-francois",
        "artistName": "Claude FrançOis",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/claude-francois_claude-francois-belles-belles-belles-official-lyric-video/600/600"
      },
      {
        "id": "claude-francois_claude-francois-c-est-comme-ca-que-l-on-s-est-aime",
        "title": "Claude FrançOis   C'Est Comme çA Que L'On S'Est Aimé",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20C'est%20comme%20%C3%A7a%20que%20l'on%20s'est%20aim%C3%A9.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20C'est%20comme%20%C3%A7a%20que%20l'on%20s'est%20aim%C3%A9.mp3",
        "artistSlug": "claude-francois",
        "artistName": "Claude FrançOis",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/claude-francois_claude-francois-c-est-comme-ca-que-l-on-s-est-aime/600/600"
      },
      {
        "id": "claude-francois_claude-francois-c-est-la-meme-chanson",
        "title": "Claude FrançOis   C'Est La MêMe Chanson",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20C'est%20la%20m%C3%AAme%20chanson.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20C'est%20la%20m%C3%AAme%20chanson.mp3",
        "artistSlug": "claude-francois",
        "artistName": "Claude FrançOis",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/claude-francois_claude-francois-c-est-la-meme-chanson/600/600"
      },
      {
        "id": "claude-francois_claude-francois-cette-annee-la",
        "title": "Claude FrançOis   Cette AnnéE Là",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20Cette%20ann%C3%A9e-l%C3%A0.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20Cette%20ann%C3%A9e-l%C3%A0.mp3",
        "artistSlug": "claude-francois",
        "artistName": "Claude FrançOis",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/claude-francois_claude-francois-cette-annee-la/600/600"
      },
      {
        "id": "claude-francois_claude-francois-chanson-populaire-audio",
        "title": "Claude FrançOis   Chanson Populaire (Audio)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20Chanson%20populaire%20(Audio).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20Chanson%20populaire%20(Audio).mp3",
        "artistSlug": "claude-francois",
        "artistName": "Claude FrançOis",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/claude-francois_claude-francois-chanson-populaire-audio/600/600"
      },
      {
        "id": "claude-francois_claude-francois-comme-d-habitude",
        "title": "Claude FrançOis   Comme D'Habitude",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20Comme%20d'habitude.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20Comme%20d'habitude.mp3",
        "artistSlug": "claude-francois",
        "artistName": "Claude FrançOis",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/claude-francois_claude-francois-comme-d-habitude/600/600"
      },
      {
        "id": "claude-francois_claude-francois-donna-donna-le-petit-garcon",
        "title": "Claude FrançOis   Donna Donna ＂Le Petit GarçOn＂",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20Donna%20Donna%20%EF%BC%82Le%20petit%20gar%C3%A7on%EF%BC%82.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20Donna%20Donna%20%EF%BC%82Le%20petit%20gar%C3%A7on%EF%BC%82.mp3",
        "artistSlug": "claude-francois",
        "artistName": "Claude FrançOis",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/claude-francois_claude-francois-donna-donna-le-petit-garcon/600/600"
      },
      {
        "id": "claude-francois_claude-francois-j-y-pense-et-puis-j-oublie",
        "title": "Claude FrançOis   J'Y Pense Et Puis J'Oublie",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20J'y%20pense%20et%20puis%20j'oublie.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20J'y%20pense%20et%20puis%20j'oublie.mp3",
        "artistSlug": "claude-francois",
        "artistName": "Claude FrançOis",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/claude-francois_claude-francois-j-y-pense-et-puis-j-oublie/600/600"
      },
      {
        "id": "claude-francois_claude-francois-je-sais",
        "title": "Claude FrançOis   Je Sais",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20Je%20sais.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20Je%20sais.mp3",
        "artistSlug": "claude-francois",
        "artistName": "Claude FrançOis",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/claude-francois_claude-francois-je-sais/600/600"
      },
      {
        "id": "claude-francois_claude-francois-je-vais-a-rio",
        "title": "Claude FrançOis   Je Vais à Rio",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20Je%20vais%20%C3%A0%20Rio.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20Je%20vais%20%C3%A0%20Rio.mp3",
        "artistSlug": "claude-francois",
        "artistName": "Claude FrançOis",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/claude-francois_claude-francois-je-vais-a-rio/600/600"
      },
      {
        "id": "claude-francois_claude-francois-la-musique-americaine-lyrics",
        "title": "Claude FrançOis   La Musique AméRicaine (Lyrics)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20La%20musique%20am%C3%A9ricaine%20(lyrics).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20La%20musique%20am%C3%A9ricaine%20(lyrics).mp3",
        "artistSlug": "claude-francois",
        "artistName": "Claude FrançOis",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/claude-francois_claude-francois-la-musique-americaine-lyrics/600/600"
      },
      {
        "id": "claude-francois_claude-francois-laisse-une-chance-a-notre-amour-1977",
        "title": "Claude FrançOis   Laisse Une Chance à Notre Amour (1977)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20Laisse%20une%20chance%20%C3%A0%20notre%20amour%20(1977).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20Laisse%20une%20chance%20%C3%A0%20notre%20amour%20(1977).mp3",
        "artistSlug": "claude-francois",
        "artistName": "Claude FrançOis",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/claude-francois_claude-francois-laisse-une-chance-a-notre-amour-1977/600/600"
      },
      {
        "id": "claude-francois_claude-francois-le-chanteur-malheureux-audio",
        "title": "Claude FrançOis   Le Chanteur Malheureux (Audio)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20Le%20chanteur%20malheureux%20(Audio).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20Le%20chanteur%20malheureux%20(Audio).mp3",
        "artistSlug": "claude-francois",
        "artistName": "Claude FrançOis",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/claude-francois_claude-francois-le-chanteur-malheureux-audio/600/600"
      },
      {
        "id": "claude-francois_claude-francois-le-lundi-au-soleil-audio",
        "title": "Claude FrançOis   Le Lundi Au Soleil (Audio)",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20Le%20lundi%20au%20soleil%20(Audio).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20Le%20lundi%20au%20soleil%20(Audio).mp3",
        "artistSlug": "claude-francois",
        "artistName": "Claude FrançOis",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/claude-francois_claude-francois-le-lundi-au-soleil-audio/600/600"
      },
      {
        "id": "claude-francois_claude-francois-le-mal-aime",
        "title": "Claude FrançOis   Le Mal Aimé",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20Le%20mal%20aim%C3%A9.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Fran%C3%A7ois%20-%20Le%20mal%20aim%C3%A9.mp3",
        "artistSlug": "claude-francois",
        "artistName": "Claude FrançOis",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/claude-francois_claude-francois-le-mal-aime/600/600"
      },
      {
        "id": "claude-francois_claude-francois-meme-si-tu-revenais",
        "title": "Claude Francois   Meme Si Tu Revenais",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Francois%20-%20Meme%20Si%20Tu%20Revenais.mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/Claude%20Francois%20-%20Meme%20Si%20Tu%20Revenais.mp3",
        "artistSlug": "claude-francois",
        "artistName": "Claude FrançOis",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/claude-francois_claude-francois-meme-si-tu-revenais/600/600"
      },
      {
        "id": "claude-francois_claude-francois-sha-la-la-hier-est-pres-de-moi",
        "title": "CLAUDE FRANÇOIS  ： SHA LA LA ( Hier Est PrèS De Moi )",
        "duration": 0,
        "url": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/CLAUDE%20FRAN%C3%87OIS%20%20%EF%BC%9A%20SHA%20LA%20LA%20(%20Hier%20est%20pr%C3%A8s%20de%20moi%20).mp3",
        "audioUrl": "/music/europe/france/chanson-fran%C3%A7aise/Claude%20Fran%C3%A7ois/CLAUDE%20FRAN%C3%87OIS%20%20%EF%BC%9A%20SHA%20LA%20LA%20(%20Hier%20est%20pr%C3%A8s%20de%20moi%20).mp3",
        "artistSlug": "claude-francois",
        "artistName": "Claude FrançOis",
        "genre": "Chanson FrançAise",
        "cover": "https://picsum.photos/seed/claude-francois_claude-francois-sha-la-la-hier-est-pres-de-moi/600/600"
      }
    ]
  }
];

export function artistsByCountry(country: string): Artist[] {
  return ARTISTS.filter(a => a.country.toLowerCase() === country.toLowerCase());
}
export function artistBySlug(slug: string): Artist | undefined {
  return ARTISTS.find(a => a.slug === slug);
}
export function allSongs(): Song[] {
  return ARTISTS.flatMap(a => a.songs);
}
export function searchAll(q: string): { artists: Artist[]; songs: Song[] } {
  const s = q.trim().toLowerCase();
  if (!s) return { artists: [], songs: [] };
  return {
    artists: ARTISTS.filter(a =>
      a.name.toLowerCase().includes(s) ||
      a.genres.join(" ").toLowerCase().includes(s) ||
      a.country.toLowerCase().includes(s)
    ).slice(0, 8),
    songs: allSongs().filter(t =>
      t.title.toLowerCase().includes(s) ||
      t.artistName.toLowerCase().includes(s)
    ).slice(0, 20),
  };
}
export function countriesWithArtists(): (Country & { count: number })[] {
  return COUNTRIES.map(c => ({ ...c, count: artistsByCountry(c.name).length }))
    .filter(c => c.count > 0);
}
export function formatDuration(sec: number): string {
  if (!sec || !isFinite(sec)) return "--:--";
  const m = Math.floor(sec / 60);
  const s = Math.floor(sec % 60);
  return `${m}:${s.toString().padStart(2, "0")}`;
}
